apiVersion: v1
kind: ConfigMap
metadata:
  name: hotel-booking-config
  namespace: hotel-booking
data:
  DB_HOST: mysql
  DB_PORT: "3306"
  DB_NAME: hotel_booking
  JWT_EXPIRATION: "86400000"
  BACKEND_URL: "http://backend-service:8081"
