apiVersion: v1
kind: Secret
metadata:
  name: hotel-booking-secret
  namespace: hotel-booking
type: Opaque
stringData:
  DB_USERNAME: hotel_user
  DB_PASSWORD: hotel_pass
  JWT_SECRET: change-this-secret-for-production
